# Generated by Django 2.0.4 on 2018-04-25 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vipr', '0003_user_charge_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='document/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_for', to='vipr.User')),
            ],
        ),
    ]
